name: Test Actions
on:
  workflow_dispatch:
  pull_request: []

jobs:
  install-singularity:
    name: Install with defaults
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Singularity install with defaults
        uses: ./
  install-singularity-v3-custom:
    name: Install with custom v3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Singularity v3 custom install
        uses: ./
        with:
          singularity-version: '3.11.0'
          go-version: '1.18.0'
  install-singularity-v4-custom:
    name: Install with custom v4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Singularity v4 custom install
        uses: ./
        with:
          singularity-version: '4.0.1'
          go-version: '1.20.0'
